apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      dnsPolicy: Default
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 8.8.8.8
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: auth
          image: sagit612/auth
          env: 
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: GOOGLE_CLIENT_ID
              value: '1064906767052-lemu93dod3focc8usrjlg1069nlc737p.apps.googleusercontent.com'
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: GOOGLE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000